-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-11-30 10:47:14 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE dim_city CASCADE CONSTRAINTS;

DROP TABLE dim_country CASCADE CONSTRAINTS;

DROP TABLE dim_date CASCADE CONSTRAINTS;

DROP TABLE dim_manager CASCADE CONSTRAINTS;

DROP TABLE dim_office CASCADE CONSTRAINTS;

DROP TABLE dim_product CASCADE CONSTRAINTS;

DROP TABLE fact_sales CASCADE CONSTRAINTS;

CREATE TABLE dim_city (
    city_id      INTEGER NOT NULL,
    city_name    VARCHAR2(1000 CHAR),
    country_id   INTEGER NOT NULL
);

ALTER TABLE dim_city ADD CONSTRAINT dim_city_pk PRIMARY KEY ( city_id );

CREATE TABLE dim_country (
    country_id     INTEGER NOT NULL,
    country_name   VARCHAR2(1000 CHAR)
);

ALTER TABLE dim_country ADD CONSTRAINT dim_country_pk PRIMARY KEY ( country_id );

CREATE TABLE dim_date (
    date_id     INTEGER NOT NULL,
    date_name   VARCHAR2(100 CHAR),
    "LEVEL"     INTEGER
);

ALTER TABLE dim_date ADD CONSTRAINT dim_date_pk PRIMARY KEY ( date_id );

CREATE TABLE dim_manager (
    manager_id   INTEGER NOT NULL,
    first_name   VARCHAR2(1000 CHAR),
    last_name    VARCHAR2(1000 CHAR)
);

ALTER TABLE dim_manager ADD CONSTRAINT dim_manager_pk PRIMARY KEY ( manager_id );

CREATE TABLE dim_office (
    office_id     INTEGER NOT NULL,
    office_name   VARCHAR2(1000 CHAR),
    city_id       INTEGER NOT NULL
);

ALTER TABLE dim_office ADD CONSTRAINT dim_office_pk PRIMARY KEY ( office_id );

CREATE TABLE dim_product (
    product_id     INTEGER NOT NULL,
    product_name   VARCHAR2(1000 CHAR)
);

ALTER TABLE dim_product ADD CONSTRAINT product_pk PRIMARY KEY ( product_id );

CREATE TABLE fact_sales (
    sale_id       INTEGER NOT NULL,
    product_id    INTEGER NOT NULL,
    manager_id    INTEGER NOT NULL,
    country_id    INTEGER NOT NULL,
    city_id       INTEGER NOT NULL,
    office_id     INTEGER NOT NULL,
    date_id       INTEGER NOT NULL,
    sale_amount   NUMBER(38, 2),
    sale_price    NUMBER(38, 2),
    sale_qty      NUMBER(38, 5)
);

ALTER TABLE fact_sales ADD CONSTRAINT fact_sales_pk PRIMARY KEY ( sale_id );

ALTER TABLE dim_city
    ADD CONSTRAINT dim_city_dim_country_fk FOREIGN KEY ( country_id )
        REFERENCES dim_country ( country_id );

ALTER TABLE dim_office
    ADD CONSTRAINT dim_office_dim_city_fk FOREIGN KEY ( city_id )
        REFERENCES dim_city ( city_id );

ALTER TABLE fact_sales
    ADD CONSTRAINT fact_sales_dim_city_fk FOREIGN KEY ( city_id )
        REFERENCES dim_city ( city_id );

ALTER TABLE fact_sales
    ADD CONSTRAINT fact_sales_dim_country_fk FOREIGN KEY ( country_id )
        REFERENCES dim_country ( country_id );

ALTER TABLE fact_sales
    ADD CONSTRAINT fact_sales_dim_date_fk FOREIGN KEY ( date_id )
        REFERENCES dim_date ( date_id );

ALTER TABLE fact_sales
    ADD CONSTRAINT fact_sales_dim_manager_fk FOREIGN KEY ( manager_id )
        REFERENCES dim_manager ( manager_id );

ALTER TABLE fact_sales
    ADD CONSTRAINT fact_sales_dim_office_fk FOREIGN KEY ( office_id )
        REFERENCES dim_office ( office_id );

ALTER TABLE fact_sales
    ADD CONSTRAINT fact_sales_dim_product_fk FOREIGN KEY ( product_id )
        REFERENCES dim_product ( product_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
